void main(){

var product =['front cam 5.5' ,'back cam 10' , 'display 4.4'];
 //.....add.......
product.add('wifi');
//....add all.....
product.addAll(['scaner finger print', 'sensor motion']);
//.......indexof....
var appleIndex = product.indexOf('wifi');
//......removeAt....
product.removeAt(appleIndex);
//.....clear......
//product.clear();
//.....fillRange.....
product.fillRange(5, 5);
//....asMap....
product.asMap();
//.....removeLast...
product.removeLast();
//....setALL....
product.setAll(0, product);
//......shuffle
product.shuffle();
//....sort.....
product.sort();
//.....cast...
product.cast();
//...insert....
product.insert(4, 'colour');
//.....
product.getRange(5, 5);
print (product);
}